#!/bin/bash

while true; do
    echo "1. Convert to Uppercase"
    echo "2. Convert to Lowercase"
    echo "3. Exit"
    read -p "Enter your choice (1/2/3): " choice

    case $choice in
        1)
            read -p "Enter a string in lowercase: " input_string
            uppercase_string=$(echo "$input_string" | tr '[:lower:]' '[:upper:]')
            echo "Uppercase: $uppercase_string"
            ;;
        2)
            read -p "Enter a string in uppercase: " input_string
            lowercase_string=$(echo "$input_string" | tr '[:upper:]' '[:lower:]')
            echo "Lowercase: $lowercase_string"
            ;;
        3)
            echo "Exiting script."
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter 1, 2, or 3."
            ;;
    esac
done
