#!/bin/bash

echo "String Case Converter"

while true; do
    echo -e "\nMenu:"
    echo "1. Convert Uppercase to Lowercase"
    echo "2. Convert Lowercase to Uppercase"
    echo "3. Exit"

    read -p "Enter your choice (1-3): " choice

    case $choice in
        1)
            read -p "Enter an UPPERCASE string: " uppercase_string
            lowercase_string=$(echo "$uppercase_string" | tr '[:upper:]' '[:lower:]')
            echo "Converted to lowercase: $lowercase_string"
            ;;
        2)
            read -p "Enter a lowercase string: " lowercase_string
            uppercase_string=$(echo "$lowercase_string" | tr '[:lower:]' '[:upper:]')
            echo "Converted to UPPERCASE: $uppercase_string"
            ;;
        3)
            echo "Exiting the script. Goodbye!"
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a number between 1 and 3."
            ;;
    esac
done
